name: Build and deploy ASP.Net Core app to Azure Web App - apiinriseservice

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_73D85DB5387C4B7293EA1F51993A967C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6B8A7C2BFD39489195A631D1BAFB2BAB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FEE4818FF6B446C49500A72E348EFF9B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'apiinriseservice'
          slot-name: 'Production'
          package: .

      - name: Debug - List files
        shell: pwsh
        run: Get-ChildItem -Recurse

      - name: Zip ca.pem file using PowerShell
        shell: pwsh
        run: |
          $zipFile = "ca.zip"
          $fileToZip = "D:\a\InRiseService\InRiseService"  # Ajuste após depurar
          Add-Type -AssemblyName System.IO.Compression.FileSystem
          [System.IO.Compression.ZipFile]::CreateFromDirectory((Get-Item $fileToZip).DirectoryName, $zipFile)
          Write-Host "Zip created: $zipFile"

      - name: Upload ca.pem to Azure Web App
        shell: pwsh
        run: |
          az webapp config appsettings set `
            --name apiinriseservice `
            --resource-group "InRiseComputadoresDev" `
            --settings CA_CERT_PATH=/home/site/wwwroot/caminho/ca.pem
          
          az webapp deployment source config-zip `
            --resource-group "InRiseComputadoresDev" `
            --name apiinriseservice `
            --src ca.zip
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZUREAPPSERVICE_CLIENTID_73D85DB5387C4B7293EA1F51993A967C }}
          AZURE_TENANT_ID: ${{ secrets.AZUREAPPSERVICE_TENANTID_6B8A7C2BFD39489195A631D1BAFB2BAB }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FEE4818FF6B446C49500A72E348EFF9B }}
