name: Build and deploy ASP.Net Core app to Azure Web App - apiinriseservice

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_73D85DB5387C4B7293EA1F51993A967C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6B8A7C2BFD39489195A631D1BAFB2BAB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FEE4818FF6B446C49500A72E348EFF9B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'apiinriseservice'
          slot-name: 'Production'
          package: .

      - name: Upload .pem file to WebApp
        run: |
          # Variáveis
          WEBAPP_NAME="apiinriseservice"
          RESOURCE_GROUP="InRiseComputadoresDev"
          PEM_FILE_PATH="./caminho/ca.pem"
          DESTINO="/home/site/wwwroot/caminho/ca.pem"

          # Obter credenciais do Kudu
          USERNAME=$(az webapp deployment list-publishing-profiles --resource-group $RESOURCE_GROUP --name $WEBAPP_NAME --query '[0].userName' -o tsv)
          PASSWORD=$(az webapp deployment list-publishing-profiles --resource-group $RESOURCE_GROUP --name $WEBAPP_NAME --query '[0].userPWD' -o tsv)

          # Subir o arquivo para o WebApp
          curl -X PUT -u "$USERNAME:$PASSWORD" \
            --upload-file $PEM_FILE_PATH \
            "https://$WEBAPP_NAME.scm.azurewebsites.net/api/vfs/$DESTINO"