name: Build and deploy ASP.Net Core app to Azure Web App - apiinriseservice

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
        
      - name: Login to Azure

        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_73D85DB5387C4B7293EA1F51993A967C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6B8A7C2BFD39489195A631D1BAFB2BAB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FEE4818FF6B446C49500A72E348EFF9B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'apiinriseservice'
          slot-name: 'Production'
          package: .

      - name: Create .pem file if not exists
        shell: pwsh
        run: |
          # Defina o caminho onde o arquivo .pem será criado
          $PEM_DIR = "caminho"
          $PEM_FILE = "$PEM_DIR/ca.pem"

          # Verifique se o diretório existe, se não, crie-o
          if (-not (Test-Path -Path $PEM_DIR)) {
            New-Item -ItemType Directory -Path $PEM_DIR -Force
          }

          # Crie o arquivo .pem com conteúdo de exemplo (substitua pelo conteúdo real do seu certificado)
          $pemContent = @"
          -----BEGIN CERTIFICATE-----
          MIIEQTCCAqmgAwIBAgIUTkpG7P62MTLXsR51K80i9uZKwd0wDQYJKoZIhvcNAQEM
          BQAwOjE4MDYGA1UEAwwvYmUyNmJmNTctYzE3OC00ZjU3LWIzYTgtYWJiODQxMDUx
          OWZlIFByb2plY3QgQ0EwHhcNMjQxMTEwMDEzNDM5WhcNMzQxMTA4MDEzNDM5WjA6
          MTgwNgYDVQQDDC9iZTI2YmY1Ny1jMTc4LTRmNTctYjNhOC1hYmI4NDEwNTE5ZmUg
          UHJvamVjdCBDQTCCAaIwDQYJKoZIhvcNAQEBBQADggGPADCCAYoCggGBAOeeZG3s
          ziPrg3Ml8xMPy/nJrlTGNQ8xm/lABrf/dGZ/umFXGcwtOquSrLyaNRvprabnkzCw
          oTOjv6BNdq9HrfVHq/LOHhtOh+hjknX3e/ziHmamMCf5zasDcvJO0mC4uYqFbMzG
          u2mCcMaxMjlUXgodtp83UOcFYI8cuWWU/fS6aVCL5HaXkOOKSB2HiEa43TVHKcz4
          NjqBp3l0H6aL5JR3fCEGrk/5eNyKAMyqkF+7AjjK9IMoyy3IYmPI0uJkSy872y+I
          gHRAdjOG60QN60v1fhVAUKsunkWZ61OtW2iNnR8MfrzNkb8MUjIp2M4bLb4euQae
          A/7LxK4v1GAir2OKuwonJsSWjyXeYZm7Xz0JXFOLlStB7cxhfCfCP6XcwD4MNhPb
          UbRz32hIZfVliKcAC33rttwFZ37FAVjJWSkwYJxr7MX2cmp7u4gWX1U6OUHIS4SP
          d4h2A0Hod7shN0uKX9X+9/YlpMuBRfOs9ffLZvcttywxMT0ka7pfdY4fYwIDAQAB
          oz8wPTAdBgNVHQ4EFgQU9sbOAzPC8Q0J2UeMLYsdB8PriKkwDwYDVR0TBAgwBgEB
          /wIBADALBgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQEMBQADggGBAIqKiVWsTNPhg1rA
          oqizWpiREDq6G/yOlBgUqWXxZLajLpk4S3Mgr+j+GYtrdb8VkLm8Lygsj0LA0sQc
          DQ6tvdk1loacDLiaLNOnqrA6IqXSTsfqK/FoIR7yd0F34oJYiwWj76CEYh98Q6bp
          FE9dgD+R0kJy/8WD1GSht3IPW7rTLAL14rsBHPmQhLo1GlQGb+KG7gYtMw2MjlZA
          fdSS5lIwTgdT+4S0b+22AZmZxX6wKqbXR5BsJuSNnlIaq8/771wt9leO1UfZjbZa
          Dc5FW27Sxp/3ohzE4+T9Z7N2+sW/Q5h4ze9NQ7a0/UDUSd7sUe9WyV+VNI6Wmew8
          IPEiG07dkQ3jHehDoMn4Wkq5H+FCJhWnjbqIYnQGRhuzhOgIrrU6EEK9MezsJj0c
          G/MUbrbAmQQxMsMY6IgkOYi4khH2VB5STpNR8N7q4WEvYfLcGXdR5UKFSnrCjFog
          sYqwEGvOb0FdlbKQuCGOnZXHxCw32B9IxfY7atMvaOx52IaprA==
          -----END CERTIFICATE-----
          "@
          
          # Crie ou sobrescreva o arquivo .pem
          Set-Content -Path $PEM_FILE -Value $pemContent
          
          # Verifique se o arquivo foi criado com sucesso
          if (Test-Path -Path $PEM_FILE) {
            Write-Host "Arquivo .pem criado com sucesso em $PEM_FILE"
          } else {
            Write-Host "Erro ao criar o arquivo .pem"
            exit 1
          }
    